-- =============================================================
-- exercises_seed.sql
-- Apex Fitness — Exercise Library Seed
--
-- Covers all 18 filter queries generated by ProgramBuilder:
--   muscles × is_compound combinations across beginner /
--   intermediate / advanced splits.
--
-- Safe to re-run: ON CONFLICT (slug) DO NOTHING.
-- System exercises have created_by = NULL.
--
-- Difficulty scale:
--   1 = beginner  (machines, basic free-weight patterns)
--   2 = intermediate (barbell compounds, technique-dependent)
--   3 = advanced  (high-skill, significant load, complex patterns)
-- =============================================================

INSERT INTO public.exercises (
  name,
  slug,
  muscle_primary,
  muscles_secondary,
  equipment,
  workout_type,
  is_compound,
  difficulty,
  instructions
) VALUES

-- ─────────────────────────────────────────────────────────────
-- CHEST — compound
-- Satisfies: muscles:["chest"] is_compound:true
-- ─────────────────────────────────────────────────────────────

(
  'Barbell bench press',
  'barbell-bench-press',
  'chest',
  ARRAY['triceps','shoulders']::muscle_group[],
  'barbell', 'strength', true, 2,
  'Lie flat on a bench, grip slightly wider than shoulder-width. Lower the bar to mid-chest under control, then press explosively to lockout. Keep the shoulder blades retracted and feet flat throughout.'
),
(
  'Incline barbell bench press',
  'incline-barbell-bench-press',
  'chest',
  ARRAY['triceps','shoulders']::muscle_group[],
  'barbell', 'strength', true, 2,
  'Set the bench to 30-45 degrees. Lower the bar to the upper chest with elbows at roughly 60 degrees from the torso. Press to full extension without flaring elbows excessively.'
),
(
  'Decline barbell bench press',
  'decline-barbell-bench-press',
  'chest',
  ARRAY['triceps']::muscle_group[],
  'barbell', 'strength', true, 2,
  'Set the bench to a 15-30 degree decline. Lower the bar to the lower chest, keeping the elbows tucked slightly. Press back to full extension with control.'
),
(
  'Dumbbell bench press',
  'dumbbell-bench-press',
  'chest',
  ARRAY['triceps','shoulders']::muscle_group[],
  'dumbbell', 'strength', true, 1,
  'Lie flat holding dumbbells at chest level, palms facing forward. Press up and slightly inward so the weights nearly touch at the top. Allows a greater range of motion than the barbell variation.'
),
(
  'Incline dumbbell bench press',
  'incline-dumbbell-bench-press',
  'chest',
  ARRAY['triceps','shoulders']::muscle_group[],
  'dumbbell', 'strength', true, 2,
  'Set the bench to 30-45 degrees. Press the dumbbells from shoulder height to full extension, allowing a natural arc so the weights converge at the top. Emphasises the upper chest.'
),
(
  'Machine chest press',
  'machine-chest-press',
  'chest',
  ARRAY['triceps','shoulders']::muscle_group[],
  'machine', 'strength', true, 1,
  'Adjust the seat so the handles are at mid-chest height. Press forward to full extension, controlling the return. Ideal for beginners learning the push pattern or for high-rep pump work.'
),
(
  'Push-up',
  'push-up',
  'chest',
  ARRAY['triceps','shoulders','core']::muscle_group[],
  'bodyweight', 'strength', true, 1,
  'Start in a high plank with hands slightly wider than shoulder-width. Lower your chest to within an inch of the floor while keeping the core braced and hips level, then push back up.'
),
(
  'Weighted dip',
  'weighted-dip',
  'chest',
  ARRAY['triceps','shoulders']::muscle_group[],
  'bodyweight', 'strength', true, 3,
  'Support yourself on parallel bars. Lean forward slightly to emphasise the chest. Lower until the upper arms are parallel to the ground, then press back up. Add a dip belt for extra load.'
),

-- ─────────────────────────────────────────────────────────────
-- CHEST — isolation
-- Satisfies: muscles:["chest"] is_compound:false
-- ─────────────────────────────────────────────────────────────

(
  'Dumbbell flye',
  'dumbbell-flye',
  'chest',
  ARRAY[]::muscle_group[],
  'dumbbell', 'strength', false, 2,
  'Lie flat with dumbbells held above the chest, elbows slightly bent. Lower the weights in a wide arc until you feel a deep chest stretch, then squeeze the pecs to bring them back together.'
),
(
  'Incline dumbbell flye',
  'incline-dumbbell-flye',
  'chest',
  ARRAY[]::muscle_group[],
  'dumbbell', 'strength', false, 2,
  'Set the bench to 30-45 degrees. Perform a flye arc, focusing on the stretch at the bottom and contraction at the top. Targets the upper chest more than the flat variation.'
),
(
  'Cable flye',
  'cable-flye',
  'chest',
  ARRAY[]::muscle_group[],
  'cable', 'strength', false, 1,
  'Set cables to high, mid, or low pulley depending on the angle desired. Bring the handles together in a wide arc, maintaining a slight elbow bend. Cables provide constant tension through the full range.'
),
(
  'Pec dec',
  'pec-dec',
  'chest',
  ARRAY[]::muscle_group[],
  'machine', 'strength', false, 1,
  'Sit with your back firmly against the pad and forearms on the arm pads. Bring the pads together in front of your chest, squeezing the pecs hard at the peak contraction. Return slowly.'
),

-- ─────────────────────────────────────────────────────────────
-- BACK — compound
-- Satisfies: muscles:["back"] is_compound:true
-- ─────────────────────────────────────────────────────────────

(
  'Conventional deadlift',
  'conventional-deadlift',
  'back',
  ARRAY['hamstrings','glutes','quads','core']::muscle_group[],
  'barbell', 'strength', true, 3,
  'Stand with the bar over mid-foot, grip just outside the legs. Hinge at the hips to lower your hands to the bar, then create full-body tension before driving the floor away. Lock out by squeezing glutes at the top.'
),
(
  'Barbell bent-over row',
  'barbell-bent-over-row',
  'back',
  ARRAY['biceps','hamstrings','core']::muscle_group[],
  'barbell', 'strength', true, 2,
  'Hinge forward to roughly 45 degrees with the bar hanging at arm length. Row the bar to the lower abdomen, leading with the elbows and squeezing the shoulder blades together at the top.'
),
(
  'Pull-up',
  'pull-up',
  'back',
  ARRAY['biceps']::muscle_group[],
  'bodyweight', 'strength', true, 2,
  'Hang from a bar with a pronated grip slightly wider than shoulder-width. Pull until the chin clears the bar, initiating by depressing the scapulae before bending the elbows. Lower fully.'
),
(
  'Chin-up',
  'chin-up',
  'back',
  ARRAY['biceps']::muscle_group[],
  'bodyweight', 'strength', true, 2,
  'Hang from a bar with a supinated (underhand) shoulder-width grip. Pull until the chin clears the bar. The supinated grip increases bicep recruitment relative to the standard pull-up.'
),
(
  'Lat pulldown',
  'lat-pulldown',
  'back',
  ARRAY['biceps']::muscle_group[],
  'cable', 'strength', true, 1,
  'Grip the bar wider than shoulder-width. Initiate by depressing the shoulder blades, then pull the bar to upper chest level. Lean back slightly, keeping the core braced.'
),
(
  'Seated cable row',
  'seated-cable-row',
  'back',
  ARRAY['biceps']::muscle_group[],
  'cable', 'strength', true, 1,
  'Sit upright at a cable row station. Pull the handle to the lower abdomen, driving the elbows back and squeezing the shoulder blades together. Avoid rocking the torso.'
),
(
  'Dumbbell single-arm row',
  'dumbbell-single-arm-row',
  'back',
  ARRAY['biceps']::muscle_group[],
  'dumbbell', 'strength', true, 1,
  'Support one hand and knee on a bench. Let the dumbbell hang from the other arm, then row it to hip height, driving the elbow toward the ceiling. Keep the spine neutral throughout.'
),
(
  'T-bar row',
  't-bar-row',
  'back',
  ARRAY['biceps','hamstrings']::muscle_group[],
  'barbell', 'strength', true, 2,
  'Stand over the loaded end of a barbell or T-bar station. Hinge forward and row the weight to the lower chest, leading with the elbows. Allows heavy loading with a neutral or overhand grip.'
),
(
  'Machine row',
  'machine-row',
  'back',
  ARRAY['biceps']::muscle_group[],
  'machine', 'strength', true, 1,
  'Adjust the chest pad and seat height. Pull the handles to the lower chest, holding the peak contraction briefly. Machines provide stability and allow training to failure safely.'
),
(
  'Rack pull',
  'rack-pull',
  'back',
  ARRAY['hamstrings','glutes']::muscle_group[],
  'barbell', 'strength', true, 3,
  'Set the safety pins just below knee height. Deadlift from this shortened range, emphasising the upper back and traps. Allows greater loading than a conventional deadlift due to the reduced range.'
),

-- ─────────────────────────────────────────────────────────────
-- BACK — isolation
-- Satisfies: muscles:["back"] is_compound:false
-- ─────────────────────────────────────────────────────────────

(
  'Face pull',
  'face-pull',
  'back',
  ARRAY['shoulders']::muscle_group[],
  'cable', 'strength', false, 1,
  'Attach a rope to a high pulley. Pull the rope toward your face while flaring the elbows out to the sides. Emphasises the rear delts and external rotators; essential for shoulder health.'
),
(
  'Straight-arm pulldown',
  'straight-arm-pulldown',
  'back',
  ARRAY[]::muscle_group[],
  'cable', 'strength', false, 1,
  'Stand at a high pulley with arms extended. Keep a slight elbow bend and pull the bar or rope down to your thighs in a sweeping arc, squeezing the lats at the bottom.'
),
(
  'Cable pullover',
  'cable-pullover',
  'back',
  ARRAY['chest']::muscle_group[],
  'cable', 'strength', false, 2,
  'Lie on a bench perpendicular to a low cable. Holding the handle at arm length over your chest, sweep back in an arc overhead, fully stretching the lats before returning.'
),

-- ─────────────────────────────────────────────────────────────
-- SHOULDERS — compound
-- Satisfies: muscles:["shoulders"] is_compound:true
-- ─────────────────────────────────────────────────────────────

(
  'Barbell overhead press',
  'barbell-overhead-press',
  'shoulders',
  ARRAY['triceps','core']::muscle_group[],
  'barbell', 'strength', true, 2,
  'Stand with the bar at shoulder level, grip slightly wider than shoulder-width. Press the bar straight up while moving your head back slightly to clear the path, then lock out overhead. Lower with control.'
),
(
  'Dumbbell shoulder press',
  'dumbbell-shoulder-press',
  'shoulders',
  ARRAY['triceps']::muscle_group[],
  'dumbbell', 'strength', true, 1,
  'Sit on an upright bench holding dumbbells at ear level. Press overhead until the arms are fully extended, then lower back to the start. The independent movement of each arm can highlight imbalances.'
),
(
  'Arnold press',
  'arnold-press',
  'shoulders',
  ARRAY['triceps']::muscle_group[],
  'dumbbell', 'strength', true, 2,
  'Begin with dumbbells in front of your face, palms facing you. As you press overhead, rotate your palms forward so they face away at the top. Reverse the rotation on the descent.'
),
(
  'Machine shoulder press',
  'machine-shoulder-press',
  'shoulders',
  ARRAY['triceps']::muscle_group[],
  'machine', 'strength', true, 1,
  'Adjust the seat and grip handles at shoulder level. Press overhead to full extension, then return to the start. The guided path makes it beginner-friendly and safe for training close to failure.'
),
(
  'Barbell upright row',
  'barbell-upright-row',
  'shoulders',
  ARRAY['biceps']::muscle_group[],
  'barbell', 'strength', true, 2,
  'Hold a barbell with a shoulder-width or slightly narrower grip. Pull the bar up along the body to chin height, leading with the elbows. Do not use a narrow grip as it stresses the shoulder joints.'
),

-- ─────────────────────────────────────────────────────────────
-- SHOULDERS — isolation
-- Satisfies: muscles:["shoulders"] is_compound:false
-- ─────────────────────────────────────────────────────────────

(
  'Dumbbell lateral raise',
  'dumbbell-lateral-raise',
  'shoulders',
  ARRAY[]::muscle_group[],
  'dumbbell', 'strength', false, 1,
  'Hold dumbbells at your sides with a slight elbow bend. Raise them out to the sides until they reach shoulder height. Avoid shrugging or swinging — keep the movement strict and controlled.'
),
(
  'Cable lateral raise',
  'cable-lateral-raise',
  'shoulders',
  ARRAY[]::muscle_group[],
  'cable', 'strength', false, 1,
  'Stand beside a low cable. Cross your arm over the body and raise the handle out to your side to shoulder height. Cables provide constant tension throughout the range, unlike dumbbells.'
),
(
  'Dumbbell front raise',
  'dumbbell-front-raise',
  'shoulders',
  ARRAY[]::muscle_group[],
  'dumbbell', 'strength', false, 1,
  'Hold dumbbells at your sides and raise them in front to shoulder height with the arms nearly straight. Alternate arms or raise both together. Targets the anterior deltoid.'
),
(
  'Dumbbell rear delt flye',
  'dumbbell-rear-delt-flye',
  'shoulders',
  ARRAY['back']::muscle_group[],
  'dumbbell', 'strength', false, 1,
  'Hinge forward until the torso is near parallel to the floor. Let the dumbbells hang, then raise them out to the sides in a wide arc, squeezing the rear delts at the top.'
),
(
  'Machine rear delt flye',
  'machine-rear-delt-flye',
  'shoulders',
  ARRAY['back']::muscle_group[],
  'machine', 'strength', false, 1,
  'Face the pad of the pec dec machine and grip the handles with arms extended. Pull back in a wide arc, keeping a slight elbow bend. Targets the posterior deltoid and upper back.'
),
(
  'Band pull-apart',
  'band-pull-apart',
  'shoulders',
  ARRAY['back']::muscle_group[],
  'band', 'strength', false, 1,
  'Hold a resistance band at shoulder height with both hands, arms extended. Pull the band apart by driving the hands out to the sides until the band touches your chest. An excellent rear delt and shoulder health exercise.'
),

-- ─────────────────────────────────────────────────────────────
-- BICEPS — isolation
-- Satisfies: muscles:["biceps"] is_compound:false
-- ─────────────────────────────────────────────────────────────

(
  'Barbell curl',
  'barbell-curl',
  'biceps',
  ARRAY[]::muscle_group[],
  'barbell', 'strength', false, 1,
  'Stand with a shoulder-width underhand grip. Curl the bar to shoulder height by flexing at the elbows, keeping the upper arms stationary. Lower fully for a complete stretch at the bottom.'
),
(
  'EZ bar curl',
  'ez-bar-curl',
  'biceps',
  ARRAY[]::muscle_group[],
  'barbell', 'strength', false, 1,
  'Use the angled EZ bar grips to curl from full extension to shoulder height. The angled grip reduces wrist strain compared to a straight barbell while still providing heavy bicep loading.'
),
(
  'Dumbbell curl',
  'dumbbell-curl',
  'biceps',
  ARRAY[]::muscle_group[],
  'dumbbell', 'strength', false, 1,
  'Hold dumbbells with palms facing forward. Curl one or both arms alternately, supinating the wrist slightly at the top to maximise the bicep contraction. Lower fully between reps.'
),
(
  'Hammer curl',
  'hammer-curl',
  'biceps',
  ARRAY[]::muscle_group[],
  'dumbbell', 'strength', false, 1,
  'Hold dumbbells with a neutral (thumbs-up) grip. Curl to shoulder height without rotating the wrist. This variation targets the brachialis and brachioradialis more than a supinated curl.'
),
(
  'Incline dumbbell curl',
  'incline-dumbbell-curl',
  'biceps',
  ARRAY[]::muscle_group[],
  'dumbbell', 'strength', false, 2,
  'Set a bench to 45-60 degrees and lean back with arms hanging freely. Curl from full extension — the inclined position creates a stretched start position that increases bicep recruitment.'
),
(
  'Cable curl',
  'cable-curl',
  'biceps',
  ARRAY[]::muscle_group[],
  'cable', 'strength', false, 1,
  'Attach a straight or EZ bar to a low pulley. Curl to shoulder height, keeping the upper arms still. Cables maintain tension at the bottom of the movement where free weights go slack.'
),
(
  'Preacher curl',
  'preacher-curl',
  'biceps',
  ARRAY[]::muscle_group[],
  'machine', 'strength', false, 1,
  'Rest the upper arms on the preacher pad and curl the weight from full extension to the top. The pad eliminates cheating and isolates the bicep. Lower very slowly for maximum eccentric stimulus.'
),
(
  'Concentration curl',
  'concentration-curl',
  'biceps',
  ARRAY[]::muscle_group[],
  'dumbbell', 'strength', false, 1,
  'Sit on a bench, bracing the working arm against the inner thigh. Curl the dumbbell slowly to shoulder height, squeezing hard at the top. One of the highest peak-contraction exercises for the bicep.'
),
(
  'Band bicep curl',
  'band-bicep-curl',
  'biceps',
  ARRAY[]::muscle_group[],
  'band', 'strength', false, 1,
  'Stand on a resistance band and curl both ends up to shoulder height with a supinated grip. Bands provide accommodating resistance — tension increases as you approach the top.'
),

-- ─────────────────────────────────────────────────────────────
-- TRICEPS — isolation
-- Satisfies: muscles:["triceps"] is_compound:false
-- ─────────────────────────────────────────────────────────────

(
  'Tricep rope pushdown',
  'tricep-rope-pushdown',
  'triceps',
  ARRAY[]::muscle_group[],
  'cable', 'strength', false, 1,
  'Attach a rope to a high pulley. Push the rope down and apart until the arms are fully extended, flaring the rope ends out at the bottom. Keep the upper arms stationary throughout.'
),
(
  'Overhead cable tricep extension',
  'overhead-cable-tricep-extension',
  'triceps',
  ARRAY[]::muscle_group[],
  'cable', 'strength', false, 1,
  'Attach a rope to a high pulley and face away. Lean forward slightly and extend the rope overhead until the arms lock out. The overhead position places the long head of the tricep under maximum stretch.'
),
(
  'Skull crusher',
  'skull-crusher',
  'triceps',
  ARRAY[]::muscle_group[],
  'barbell', 'strength', false, 2,
  'Lie on a flat bench with an EZ bar or barbell extended overhead. Lower the bar toward your forehead by flexing only at the elbows, then extend back to the top. Keep the upper arms perpendicular to the floor.'
),
(
  'Dumbbell overhead tricep extension',
  'dumbbell-overhead-tricep-extension',
  'triceps',
  ARRAY[]::muscle_group[],
  'dumbbell', 'strength', false, 1,
  'Hold a single dumbbell with both hands overhead. Lower it behind your head by bending the elbows, then press back to full extension. Can also be performed with one arm at a time.'
),
(
  'Close-grip bench press',
  'close-grip-bench-press',
  'triceps',
  ARRAY['chest','shoulders']::muscle_group[],
  'barbell', 'strength', false, 2,
  'Use a shoulder-width or slightly narrower grip on a flat bench. Lower the bar to the lower chest and press back to lockout. The narrow grip shifts emphasis from the chest to the triceps.'
),
(
  'Cable kickback',
  'cable-kickback',
  'triceps',
  ARRAY[]::muscle_group[],
  'cable', 'strength', false, 1,
  'Hinge forward and attach a single handle to a low cable. Keeping the upper arm parallel to the floor, extend the forearm fully behind you. Squeeze the tricep hard at peak extension.'
),
(
  'Machine tricep press',
  'machine-tricep-press',
  'triceps',
  ARRAY[]::muscle_group[],
  'machine', 'strength', false, 1,
  'Sit at a tricep press machine with the handles at shoulder height. Press down to full extension without flaring the elbows. A stable, joint-friendly option for high-rep tricep training.'
),
(
  'Bodyweight tricep dip',
  'bodyweight-tricep-dip',
  'triceps',
  ARRAY['chest','shoulders']::muscle_group[],
  'bodyweight', 'strength', false, 2,
  'Support yourself on parallel bars, staying upright rather than leaning forward. Lower until the elbows reach 90 degrees, then press back to lockout. An upright torso maximises tricep engagement.'
),

-- ─────────────────────────────────────────────────────────────
-- QUADS — compound
-- Satisfies: muscles:["quads"] is_compound:true
--            muscles:["glutes","quads"] is_compound:true
--            muscles:["hamstrings","quads"] is_compound:true
-- ─────────────────────────────────────────────────────────────

(
  'Barbell back squat',
  'barbell-back-squat',
  'quads',
  ARRAY['glutes','hamstrings','core']::muscle_group[],
  'barbell', 'strength', true, 3,
  'Position the bar on the upper back, feet shoulder-width apart. Squat to at least parallel by sitting back and down, keeping the chest tall and knees tracking over the toes. Drive through the full foot to stand.'
),
(
  'Barbell front squat',
  'barbell-front-squat',
  'quads',
  ARRAY['glutes','core']::muscle_group[],
  'barbell', 'strength', true, 3,
  'Hold the bar in a front rack position at shoulder level. Squat keeping the torso upright and elbows high. The front-loaded position demands greater quad and core involvement than the back squat.'
),
(
  'Leg press',
  'leg-press',
  'quads',
  ARRAY['glutes','hamstrings']::muscle_group[],
  'machine', 'strength', true, 1,
  'Place feet shoulder-width apart on the platform. Lower the sled until the knees reach 90 degrees, then press to near-lockout. Foot position can be varied to shift emphasis between quads, hamstrings, and glutes.'
),
(
  'Hack squat',
  'hack-squat',
  'quads',
  ARRAY['glutes','hamstrings']::muscle_group[],
  'machine', 'strength', true, 2,
  'Position yourself on the machine with shoulders under the pads and feet low on the platform. Descend to 90 degrees and press back up. The forward lean isolates the quads with less lower back stress than a barbell squat.'
),
(
  'Bulgarian split squat',
  'bulgarian-split-squat',
  'quads',
  ARRAY['glutes','hamstrings']::muscle_group[],
  'dumbbell', 'strength', true, 2,
  'Elevate the rear foot on a bench, holding dumbbells at your sides. Lower the rear knee toward the floor until the front thigh is parallel. An excellent unilateral exercise for quad and glute development.'
),
(
  'Dumbbell lunge',
  'dumbbell-lunge',
  'quads',
  ARRAY['glutes','hamstrings']::muscle_group[],
  'dumbbell', 'strength', true, 1,
  'Step forward and lower the rear knee toward the ground, keeping the torso upright. Drive through the front heel to step back to the start. Can be performed walking or stationary.'
),
(
  'Barbell lunge',
  'barbell-lunge',
  'quads',
  ARRAY['glutes','hamstrings']::muscle_group[],
  'barbell', 'strength', true, 2,
  'Hold a barbell on the upper back as in a squat. Step forward into a lunge, lowering the rear knee close to the floor, then push back. The barbell increases loading compared to the dumbbell version.'
),
(
  'Goblet squat',
  'goblet-squat',
  'quads',
  ARRAY['glutes','core']::muscle_group[],
  'kettlebell', 'strength', true, 1,
  'Hold a kettlebell or dumbbell at chest height with both hands. Squat down between the arms, keeping the chest tall and elbows inside the knees. An excellent technique builder for beginners.'
),

-- ─────────────────────────────────────────────────────────────
-- QUADS — isolation
-- Satisfies: muscles:["quads"] is_compound:false
-- ─────────────────────────────────────────────────────────────

(
  'Leg extension',
  'leg-extension',
  'quads',
  ARRAY[]::muscle_group[],
  'machine', 'strength', false, 1,
  'Sit with the pad across the lower shins. Extend the legs to full lockout, squeezing the quads at the top. Lower slowly for a full stretch. A pure quad isolation movement with no hip involvement.'
),
(
  'Dumbbell step-up',
  'dumbbell-step-up',
  'quads',
  ARRAY['glutes']::muscle_group[],
  'dumbbell', 'strength', false, 2,
  'Hold dumbbells and step onto a box or bench with one foot. Drive through the heel to stand fully on the box, keeping the torso upright. Step down with control. Develops single-leg quad strength.'
),

-- ─────────────────────────────────────────────────────────────
-- HAMSTRINGS — compound
-- Satisfies: muscles:["hamstrings"] is_compound:true
--            muscles:["glutes","hamstrings"] is_compound:true
--            muscles:["hamstrings","quads"] is_compound:true
-- ─────────────────────────────────────────────────────────────

(
  'Romanian deadlift',
  'romanian-deadlift',
  'hamstrings',
  ARRAY['glutes','back']::muscle_group[],
  'barbell', 'strength', true, 2,
  'Hold the bar at hip level, then hinge at the hips — pushing them back — while lowering the bar down the legs. Descend until you feel a strong hamstring stretch, then drive the hips forward to return.'
),
(
  'Dumbbell Romanian deadlift',
  'dumbbell-romanian-deadlift',
  'hamstrings',
  ARRAY['glutes','back']::muscle_group[],
  'dumbbell', 'strength', true, 1,
  'Hold dumbbells in front of the thighs. Hinge at the hips and lower the dumbbells along the legs until you feel a hamstring stretch. Drive the hips forward to return. Easier to learn than the barbell version.'
),
(
  'Good morning',
  'good-morning',
  'hamstrings',
  ARRAY['glutes','back']::muscle_group[],
  'barbell', 'strength', true, 3,
  'Position a light barbell on the upper back. With a slight knee bend, hinge forward at the hips until the torso is near parallel to the floor, then drive the hips forward to stand. Keep the back neutral throughout.'
),
(
  'Sumo deadlift',
  'sumo-deadlift',
  'hamstrings',
  ARRAY['glutes','quads','back']::muscle_group[],
  'barbell', 'strength', true, 3,
  'Stand with a wide stance and toes pointed out. Grip the bar with a narrower grip inside the legs. The wide stance shifts more load to the glutes and inner thighs compared to a conventional deadlift.'
),
(
  'Barbell hip thrust',
  'barbell-hip-thrust',
  'glutes',
  ARRAY['hamstrings','quads']::muscle_group[],
  'barbell', 'strength', true, 2,
  'Rest your upper back on a bench, bar across your hips. Drive through the heels and squeeze the glutes to extend the hips fully. The peak contraction at full hip extension is critical for glute development.'
),

-- ─────────────────────────────────────────────────────────────
-- HAMSTRINGS — isolation
-- Satisfies: muscles:["hamstrings"] is_compound:false
-- ─────────────────────────────────────────────────────────────

(
  'Lying leg curl',
  'lying-leg-curl',
  'hamstrings',
  ARRAY[]::muscle_group[],
  'machine', 'strength', false, 1,
  'Lie face-down with the pad just above the heels. Curl the pad toward your glutes through a full range of motion. Avoid letting the hips rise off the pad, which shifts load away from the hamstrings.'
),
(
  'Seated leg curl',
  'seated-leg-curl',
  'hamstrings',
  ARRAY[]::muscle_group[],
  'machine', 'strength', false, 1,
  'Sit with the pad just above the ankles. Curl the pad down toward the floor, holding the peak contraction briefly. The seated position stretches the hamstrings at the top, increasing the range of motion.'
),
(
  'Nordic hamstring curl',
  'nordic-hamstring-curl',
  'hamstrings',
  ARRAY[]::muscle_group[],
  'bodyweight', 'strength', false, 3,
  'Kneel with your feet anchored and lower your torso toward the floor by extending the knees, braking the descent as long as possible with the hamstrings. One of the most effective exercises for hamstring injury prevention.'
),

-- ─────────────────────────────────────────────────────────────
-- GLUTES — compound
-- Satisfies: muscles:["glutes","quads"] is_compound:true
--            muscles:["glutes","hamstrings"] is_compound:true
-- (barbell-hip-thrust already inserted above for both)
-- ─────────────────────────────────────────────────────────────

(
  'Dumbbell hip thrust',
  'dumbbell-hip-thrust',
  'glutes',
  ARRAY['hamstrings']::muscle_group[],
  'dumbbell', 'strength', true, 1,
  'Rest upper back on a bench and hold a dumbbell on the hips. Drive through the heels to extend the hips fully, squeezing the glutes hard at the top. A beginner-friendly alternative to the barbell version.'
),
(
  'Glute bridge',
  'glute-bridge',
  'glutes',
  ARRAY['hamstrings']::muscle_group[],
  'bodyweight', 'strength', true, 1,
  'Lie on your back with knees bent and feet flat. Drive through the heels to lift the hips until the body forms a straight line from knees to shoulders. Squeeze the glutes hard at the top before lowering.'
),
(
  'Sumo squat',
  'sumo-squat',
  'glutes',
  ARRAY['quads','hamstrings']::muscle_group[],
  'dumbbell', 'strength', true, 1,
  'Hold a dumbbell or kettlebell between the legs with a wide stance and toes angled out. Squat down between the legs. The wide stance shifts emphasis toward the glutes and inner thighs.'
),

-- ─────────────────────────────────────────────────────────────
-- GLUTES — isolation
-- Satisfies: muscles:["glutes"] is_compound:false
-- ─────────────────────────────────────────────────────────────

(
  'Cable glute kickback',
  'cable-glute-kickback',
  'glutes',
  ARRAY['hamstrings']::muscle_group[],
  'cable', 'strength', false, 1,
  'Attach an ankle strap to a low cable. Stand facing the cable machine and kick the working leg back and up, squeezing the glute hard at the top. Keep the torso stable and avoid rotating the hips.'
),
(
  'Machine hip abduction',
  'machine-hip-abduction',
  'glutes',
  ARRAY[]::muscle_group[],
  'machine', 'strength', false, 1,
  'Sit in the machine with the pads on the outer thighs. Push the pads apart by abducting the hips, squeezing the glute medius at the end range. Lower slowly for an eccentric challenge.'
),
(
  'Donkey kick',
  'donkey-kick',
  'glutes',
  ARRAY['hamstrings']::muscle_group[],
  'bodyweight', 'strength', false, 1,
  'On all fours, kick one leg back and up while keeping the knee bent at 90 degrees. Squeeze the glute at the top of the movement. Can be loaded with a resistance band or cable ankle strap.'
),

-- ─────────────────────────────────────────────────────────────
-- CALVES — isolation
-- Satisfies: muscles:["calves"] is_compound:false
-- ─────────────────────────────────────────────────────────────

(
  'Standing calf raise',
  'standing-calf-raise',
  'calves',
  ARRAY[]::muscle_group[],
  'machine', 'strength', false, 1,
  'Stand on the platform with the pads on your shoulders and the balls of your feet on the edge. Lower your heels fully for a deep stretch, then rise up onto your toes as high as possible. Hold the peak briefly.'
),
(
  'Seated calf raise',
  'seated-calf-raise',
  'calves',
  ARRAY[]::muscle_group[],
  'machine', 'strength', false, 1,
  'Sit with the pad across your lower thighs and the balls of your feet on the platform. The seated position bends the knee, which neutralises the gastrocnemius and isolates the soleus. Full range of motion is essential.'
),
(
  'Leg press calf raise',
  'leg-press-calf-raise',
  'calves',
  ARRAY[]::muscle_group[],
  'machine', 'strength', false, 1,
  'Position only the balls of your feet at the bottom edge of the leg press platform. With the legs nearly extended, push through the toes to plantarflex fully, then lower for a complete stretch.'
),
(
  'Dumbbell single-leg calf raise',
  'dumbbell-single-leg-calf-raise',
  'calves',
  ARRAY[]::muscle_group[],
  'dumbbell', 'strength', false, 1,
  'Hold a dumbbell and stand on one foot on the edge of a step. Lower the heel fully, then rise onto your toes. Single-leg loading provides a strong stimulus without needing a dedicated machine.'
),
(
  'Donkey calf raise',
  'donkey-calf-raise',
  'calves',
  ARRAY[]::muscle_group[],
  'machine', 'strength', false, 2,
  'Hinge forward with hips at 90 degrees, pads resting on the lower back. Perform a calf raise from a fully stretched position. The hip-flexed position increases gastrocnemius stretch for greater muscle activation.'
),

-- ─────────────────────────────────────────────────────────────
-- CORE — isolation
-- Satisfies: muscles:["core"] is_compound:false
-- ─────────────────────────────────────────────────────────────

(
  'Plank',
  'plank',
  'core',
  ARRAY[]::muscle_group[],
  'bodyweight', 'strength', false, 1,
  'Hold a push-up position with forearms or hands on the floor. Brace the core to maintain a straight line from head to heels. Avoid letting the hips sag or pike. Progress by extending hold time.'
),
(
  'Cable crunch',
  'cable-crunch',
  'core',
  ARRAY[]::muscle_group[],
  'cable', 'strength', false, 1,
  'Kneel in front of a high pulley holding a rope behind your head. Flex the spine to crunch the ribcage toward the pelvis, resisting the pull of the cable. Cables allow progressive overloading of the abs.'
),
(
  'Hanging leg raise',
  'hanging-leg-raise',
  'core',
  ARRAY[]::muscle_group[],
  'bodyweight', 'strength', false, 2,
  'Hang from a pull-up bar with the legs straight. Raise your legs to 90 degrees or higher by flexing at the hips, avoiding swinging. Keep the movement slow and controlled to maximise tension.'
),
(
  'Ab wheel rollout',
  'ab-wheel-rollout',
  'core',
  ARRAY['back','shoulders']::muscle_group[],
  'bodyweight', 'strength', false, 3,
  'Kneel on the floor and grip the ab wheel with both hands. Roll forward as far as possible while keeping the back flat, then use the core to pull the wheel back. One of the most demanding anti-extension core exercises.'
),
(
  'Decline crunch',
  'decline-crunch',
  'core',
  ARRAY[]::muscle_group[],
  'bodyweight', 'strength', false, 1,
  'Lie on a decline bench with feet secured. Curl the ribcage toward the pelvis through a full range of motion. Avoid pulling on the neck; the hands should lightly support the head.'
),
(
  'Russian twist',
  'russian-twist',
  'core',
  ARRAY[]::muscle_group[],
  'bodyweight', 'strength', false, 1,
  'Sit with your hips flexed and feet hovering or anchored. Rotate the torso from side to side, touching the floor beside each hip. Load with a plate or medicine ball to increase difficulty.'
),
(
  'Dead bug',
  'dead-bug',
  'core',
  ARRAY[]::muscle_group[],
  'bodyweight', 'strength', false, 1,
  'Lie on your back with arms extended toward the ceiling and knees at 90 degrees. Lower one arm and the opposite leg toward the floor while pressing your lower back into the ground. Return and alternate sides.'
),
(
  'Pallof press',
  'pallof-press',
  'core',
  ARRAY[]::muscle_group[],
  'cable', 'strength', false, 2,
  'Stand side-on to a cable set at chest height. Hold the handle at your chest, then press straight out, resisting the rotational pull of the cable. An anti-rotation exercise that builds functional core stability.'
),

-- ─────────────────────────────────────────────────────────────
-- FULL BODY / CARDIO / HIIT
-- ─────────────────────────────────────────────────────────────

(
  'Kettlebell swing',
  'kettlebell-swing',
  'glutes',
  ARRAY['hamstrings','back','core']::muscle_group[],
  'kettlebell', 'strength', true, 2,
  'Hinge at the hips and swing the kettlebell back between the legs, then drive the hips forward explosively to propel it to shoulder height. The movement is a hip hinge, not a squat; let the glutes do the work.'
),
(
  'Barbell thruster',
  'barbell-thruster',
  'quads',
  ARRAY['glutes','shoulders','core']::muscle_group[],
  'barbell', 'hiit', true, 3,
  'Hold the bar in a front rack position. Perform a front squat, then use the upward momentum to press the bar overhead in one continuous movement. A demanding full-body exercise used in conditioning work.'
),
(
  'Box jump',
  'box-jump',
  'quads',
  ARRAY['glutes','hamstrings','calves']::muscle_group[],
  'bodyweight', 'hiit', true, 2,
  'Stand in front of a plyo box, dip into a quarter squat, then jump onto the box landing softly with bent knees. Step down (do not jump down) to protect the Achilles tendon. Develops lower-body power.'
),
(
  'Farmer carry',
  'farmer-carry',
  'core',
  ARRAY['back','shoulders','glutes']::muscle_group[],
  'dumbbell', 'strength', true, 1,
  'Hold heavy dumbbells or kettlebells at your sides and walk for a set distance or time. Keep the shoulders packed, core braced, and stride controlled. An effective loaded carry for full-body strength and grip.'
),
(
  'Sled push',
  'sled-push',
  'quads',
  ARRAY['glutes','hamstrings','core']::muscle_group[],
  'machine', 'hiit', true, 2,
  'Load a sled and drive it across the floor by pushing with extended arms and taking short, powerful steps. Lean into the sled at roughly 45 degrees. A low-impact conditioning tool that develops leg drive.'
)

ON CONFLICT (slug) DO NOTHING;

-- =============================================================
-- Verification query — run after seeding to confirm coverage
-- =============================================================
-- SELECT
--   muscle_primary,
--   is_compound,
--   COUNT(*) AS exercise_count
-- FROM public.exercises
-- WHERE created_by IS NULL
-- GROUP BY muscle_primary, is_compound
-- ORDER BY muscle_primary, is_compound;